apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
        environment: development
    spec:
      initContainers:
      - name: render-config
        image: alpine:3.20
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        command:
          - sh
          - -c
          - |
            apk add --no-cache gettext
            envsubst < /config-template/prometheus.yml.template > /etc/prometheus/prometheus.yml
        envFrom:
          - configMapRef:
              name: global-config
        volumeMounts:
          - name: config-template
            mountPath: /config-template
          - name: rendered-config
            mountPath: /etc/prometheus

      containers:
      - name: prometheus
        image: prom/prometheus:v2.52.0
        args:
          - --config.file=/etc/prometheus/prometheus.yml
        ports:
        - containerPort: 9090
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        volumeMounts:
        - name: rendered-config
          mountPath: /etc/prometheus
      volumes:
      - name: config-template
        configMap:
          name: prometheus-config-template
      - name: rendered-config
        emptyDir: {}
