apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml

configMapGenerator:
  - name: prometheus-config-template
    files:
      - prometheus.yml.template=prometheus.yml.template
  - name: prometheus-rules
    files:
      - prometheus-rules.yml

generatorOptions:
  disableNameSuffixHash: true
