apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api-blue
  namespace: observability
  labels:
    app: demo-api
    version: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-api
      version: blue
  template:
    metadata:
      labels:
        app: demo-api
        version: blue
        environment: development
    spec:
      containers:
        - name: demo-api
          image: dannyanko/infra-demo-api:v3
          env:
            - name: VERSION
              value: "blue"
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "400m"
              memory: "1Gi"
          imagePullPolicy: Always
