apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: demo-api-backendconfig
  namespace: observability
spec:
  securityPolicy:
    name: demo-api-policy   # 👈 must match Cloud Armor policy name
