resources:
  - prometheus/
  - grafana/
  - kube-state-metrics/

namespace: observability

secretGenerator:
  - envs:
      - secret.env
    name: global-secret

generatorOptions:
  disableNameSuffixHash: true
