apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: demo-api-dashboard
    files:
      - demo-api-dashboard.json=demo-api-dashboard.json

generatorOptions:
  disableNameSuffixHash: true