name: Terraform Apply

on:
  push:
    branches:
      - main
    paths:
      - "terraform/**"

jobs:
  terraform-apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up GCP credentials
        run: |
          printf '%s' "${{ secrets.GCP_TF_KEY }}" > $HOME/gcp-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcp-key.json" >> $GITHUB_ENV

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file=terraform.tfvars
        working-directory: terraform
